<?php

// This file is automatically generated, please do not edit it.
// To update configuration, use bin/setup plugins:* commands.

use Alchemy\Phrasea\CommandLineApplication;

return call_user_func(function (CommandLineApplication $cli) {
    return $cli;
}, $cli);
